Add runEffCat
coot/free-category pull request #33
Opened 2020-09-08 09:27 UTC by turion

2020-10-18 14:29 UTC, coot requested changes
LGTM, just a minor stylistic change.

2020-10-18 14:29 UTC, coot commented on src/Control/Category/FreeEffect.hs
> +-- | Join all effects in a free effectful category 'EffCat'.
```suggestion
-- | Join all effects in a free effectful category 'EffCat'.
--
```

2020-10-19 10:19 UTC, coot approved these changes
Thanks; please squash the two commits, and it can be merged.

2020-10-19 13:56 UTC, turion commented
Done.

2020-10-19 18:11 UTC, merged